version: '3'
services:
    ruby:
        build:
            context: .
            dockerfile: docker/ruby/Dockerfile
        ports:
            - 80:9292
        volumes:
            - .:/app:rw
            - data:/gems
        env_file: docker/ruby/.env
        container_name: la-mulana-tools

    postgres:
        image: postgres:15.2
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/postgresql/data
        env_file: ./docker/postgres/config

    mailhog:
        image: mailhog/mailhog
        ports:
          - 8025:8025
        expose:
          - 1025

volumes:
    data:
