inventory1:
  name: 'Chain Whip'
inventory2:
  name: 'Flail Whip'
inventory3:
  name: 'Knife'
inventory4:
  name: 'Keysword'
inventory5:
  name: 'Axe'
inventory6:
  name: 'Katana'
inventory7:
  name: 'Empowered Keysword'
inventory8:
  name: 'Shurikens'
inventory9:
  name: 'Rolling Shurikens'
inventory10:
  name: 'Earth Spears'
inventory11:
  name: 'Flare Gun'
inventory12:
  name: 'Bombs'
inventory13:
  name: 'Chakrams'
inventory14:
  name: 'Caltrops'
inventory15:
  name: 'Pistol'
inventory16:
  name: 'Buckler'
inventory17:
  name: 'Silver Shield'
inventory18:
  name: 'Angel Shield'
inventory19:
  name: 'Ankh Jewel'
inventory20:
  name: "Hand Scanner"
inventory21:
  name: "Djed Pillar"
inventory22:
  name: "Mini Doll"
inventory23:
  name: "Magatama Jewel"
inventory24:
  name: "Cog of the Soul"
inventory25:
  name: "Lit Lamp of Time"
inventory26:
  name: "Pochette Key"
inventory27:
  name: "Dragon Bone"
inventory28:
  name: "Crystal Skull"
inventory29:
  name: "Vessel"
inventory30:
  name: "Pepper"
inventory31:
  name: "Woman Statue"
inventory32:
  name: "Key of Eternity"
inventory33:
  name: "Serpent Staff"
inventory34:
  name: "Talisman"
inventory36:
  name: "Waterproof Case"
inventory37:
  name: "Heatproof Case"
inventory38:
  name: "Shell Horn"
inventory39:
  name: "Glove"
inventory40:
  name: "Holy Grail"
inventory41:
  name: "Isis' Pendant"
inventory42:
  name: "Crucifix"
inventory43:
  name: "Helment"
inventory44:
  name: "Grapple Claw"
inventory45:
  name: "Bronze Mirror"
inventory46:
  name: "Eye of Truth"
inventory47:
  name: "Ring"
inventory48:
  name: "Scalesphere"
inventory49:
  name: "Gauntlet"
inventory50:
  name: "Anchor"
inventory51:
  name: "Plane Model"
inventory52:
  name: "Philosophers' Ocarina"
inventory53:
  name: "Feather"
inventory54:
  name: "Book of the Dead"
inventory55:
  name: "Fairy Clothes"
inventory56:
  name: "Scriptures"
inventory57:
  name: "Hermes' Boots"
inventory58:
  name: "Fruit of Eden"
inventory59:
  name: "Twin Statue"
inventory60:
  name: "Bracelet"
inventory61:
  name: "Perfume"
inventory62:
  name: "Spauler"
inventory63:
  name: "Dimensional Key"
inventory64:
  name: "Ice Cape"
inventory65:
  name: "Originl Seal (1)"
inventory66:
  name: "Birth Seal (2)"
inventory67:
  name: "Life Seal (3)"
inventory68:
  name: "Death Seal (4)"
inventory71:
  name: "Treasures"
inventory72:
  name: "Diary"
inventory73:
  name: "Mulana Talisman"
inventory74:
  name: "Provocative Bathing Suit"
inventory75:
  name: "Silver Shield (Fake)"
inventory76:
  name: "MSX2"
inventory77:
  name: "Medicine (Yellow)"
inventory78:
  name: "Medicine (Green)"
inventory79:
  name: "Medicine (Red)"
inventory80:
  name: "Unlit Lamp of Time"
inventory81:
  name: "Maternity Statue"
inventory82:
  name: "Holy Grail (Broken)"
inventory83:
  name: "Holy Grail (Full)"
inventory84:
  name: "Secret Treasure of Life"
inventory85:
  name: "Glyph Reader (reader.exe)"
inventory86:
  name: "Xelpud Mailer (xmailer.exe)"
inventory87:
  name: "Yagoo Map Reader (yagomap.exe)"
inventory88:
  name: "Yagoo Map Street (yagostr.exe)"
inventory89:
  name: "TextTrax (bunemon.exe)"
inventory90:
  name: "Additional Text Memory (bunplus.exe)"
inventory91:
  name: "Snapshots (torude.exe)"
inventory92:
  name: "Guild (guild.exe)"
inventory93:
  name: "Mantra (mantra.exe)"
inventory94:
  name: "Enga Musica (emusic.exe)"
inventory95:
  name: "Beo La-Mulana (beolamu.exe)"
inventory96:
  name: "Death Village (deathv.exe)"
inventory97:
  name: "Rose and Camellia (randc.exe)"
inventory98:
  name: "Space Capster II (capstar.exe)"
inventory99:
  name: "Lonely Moving House (move.exe)"
inventory100:
  name: "Mekuri Master (mekuri.exe)"
inventory101:
  name: "Bounce Shot (bounce.exe)"
inventory102:
  name: "Miracle Witch (miracle.exe)"
inventory103:
  name: "Future Development Company (mirai.exe)"
inventory104:
  name: "La-Mulana (lamulana.exe)"
inventory105:
  name: "Weights"
inventory106:
  name: "Coins"
inventory107:
  name: "Shuriken Ammo"
inventory108:
  name: "Rolling Shuriken Ammo"
inventory109:
  name: "Earth Spear Ammo"
inventory110:
  name: "Flare Gun Ammo"
inventory111:
  name: "Bomb Ammo"
inventory112:
  name: "Chakram Ammo"
inventory113:
  name: "Caltrop Ammo"
inventory114:
  name: "Pistol Clip Ammo"
inventory116:
  name: "Pistol Bullet Ammo"
