inventory1:
  name: 'Chain Whip'
inventory2:
  name: 'Flail Whip'
inventory3:
  name: 'Knife'
inventory4:
  name: 'Keysword'
inventory5:
  name: 'Axe'
inventory6:
  name: 'Katana'
inventory7:
  name: 'Empowered Keysword'
inventory8:
  name: 'Shurikens'
inventory9:
  name: 'Rolling Shurikens'
inventory10:
  name: 'Earth Spears'
inventory11:
  name: 'Flare Gun'
inventory12:
  name: 'Bombs'
inventory13:
  name: 'Chakrams'
inventory14:
  name: 'Caltrops'
inventory15:
  name: 'Pistol'
inventory16:
  name: 'Buckler'
inventory17:
  name: 'Silver Shield'
inventory18:
  name: 'Angel Shield'
inventory19:
  name: 'Ankh Jewel'
inventory20:
  name: "invus-scanner"
inventory21:
  name: "invus-pillar"
inventory22:
  name: "invus-doll"
inventory23:
  name: "invus-magatama"
inventory24:
  name: "invus-cog"
inventory25:
  name: "invus-lamp-lit"
inventory26:
  name: "invus-pochette"
inventory27:
  name: "invus-dragonb"
inventory28:
  name: "invus-cskull"
inventory29:
  name: "invus-vessel"
inventory30:
  name: "invus-pepper"
inventory31:
  name: "invus-woman"
inventory32:
  name: "invus-endless-key"
inventory33:
  name: "invus-serpent"
inventory34:
  name: "invus-talisman"
inventory35:
  name: "inv-mystery-23"
inventory36:
  name: "invtr-water-case"
inventory37:
  name: "invtr-heat-case"
inventory38:
  name: "invtr-shell-horn"
inventory39:
  name: "invtr-glove"
inventory40:
  name: "invtr-grail"
inventory41:
  name: "invtr-isispendant"
inventory42:
  name: "invtr-crucifix"
inventory43:
  name: "invtr-helmet"
inventory44:
  name: "invtr-grapple"
inventory45:
  name: "invtr-mirror"
inventory46:
  name: "invtr-eye-truth"
inventory47:
  name: "invtr-ring"
inventory48:
  name: "invtr-scale"
inventory49:
  name: "invtr-gauntlet"
inventory50:
  name: "invtr-anchor"
inventory51:
  name: "invtr-plane"
inventory52:
  name: "invtr-ocarina"
inventory53:
  name: "invtr-feather"
inventory54:
  name: "invtr-book"
inventory55:
  name: "invtr-clothes"
inventory56:
  name: "invtr-scriptures"
inventory57:
  name: "invtr-hermes"
inventory58:
  name: "invtr-fruit"
inventory59:
  name: "invtr-twin-statue"
inventory60:
  name: "invtr-bracelet"
inventory61:
  name: "invtr-perfume"
inventory62:
  name: "invtr-spaulder"
inventory63:
  name: "invtr-dimension-key"
inventory64:
  name: "invtr-icecape"
inventory65:
  name: "invseal-1"
inventory66:
  name: "invseal-2"
inventory67:
  name: "invseal-3"
inventory68:
  name: "invseal-4"
inventory69:
  name: "inv-sacredorb"
  notes: "only set briefly on collecting one, internally causes an increase in max hp and a refill"
inventory70:
  name: "maps"
inventory71:
  name: "invtr-treasures"
inventory72:
  name: "invus-diary"
inventory73:
  name: "invus-lamulana"
inventory74:
  name: "inv-forbidden"
inventory75:
  name: "invus-shield-fake"
inventory76:
  name: "invtr-msx2"
inventory77:
  name: "invus-medicine"
inventory78:
  name: "invus-medicineg"
inventory79:
  name: "invus-mediciner"
inventory80:
  name: "invus-lamp-unlit"
inventory81:
  name: "invus-maternity"
inventory82:
  name: "invtr-grailbr"
inventory83:
  name: "invtr-grailfull"
inventory84:
  name: "invtr-secrettroflife"
inventory85:
  name: "invsf-reader"
inventory86:
  name: "invsf-xmailer"
inventory87:
  name: "invsf-yagomap"
inventory88:
  name: "invsf-yagostr"
inventory89:
  name: "invsf-bunemon"
inventory90:
  name: "invsf-bunplus"
inventory91:
  name: "invsf-torude"
inventory92:
  name: "invsf-guild"
inventory93:
  name: "invsf-mantra"
inventory94:
  name: "invsf-emusic"
inventory95:
  name: "invsf-beolamu"
inventory96:
  name: "invsf-deathv"
inventory97:
  name: "invsf-randc"
inventory98:
  name: "invsf-capstar"
inventory99:
  name: "invsf-move"
inventory100:
  name: "invsf-mekuri"
inventory101:
  name: "invsf-bounce"
inventory102:
  name: "invsf-miracle"
inventory103:
  name: "invsf-mirai"
inventory104:
  name: "invsf-lamulana"
inventory105:
  name: "weights"
inventory106:
  name: "coins"
inventory107:
  name: "ammo-shuriken"
inventory108:
  name: "ammo-roll-shuriken"
inventory109:
  name: "ammo-spear"
inventory110:
  name: "ammo-flare"
inventory111:
  name: "ammo-bomb"
inventory112:
  name: "ammo-chakram"
inventory113:
  name: "ammo-caltrop"
inventory114:
  name: "ammo-clip"
inventory115:
  name: "ammo-mystery-73"
inventory116:
  name: "ammo-bullet"
